package com.r3944realms.modernlifepatch.datagen.provider;

import com.r3944realms.modernlifepatch.ModernLifePatch;
import net.minecraft.data.DataGenerator;
import net.minecraft.data.tags.BlockTagsProvider;
import net.minecraft.data.tags.ItemTagsProvider;
import net.minecraftforge.common.data.ExistingFileHelper;
import org.jetbrains.annotations.Nullable;

public class ModItemTagProvider extends ItemTagsProvider {
    public ModItemTagProvider(DataGenerator dataGenerator, BlockTagsProvider tagsProvider, @Nullable ExistingFileHelper existingFileHelper) {
        super(dataGenerator, tagsProvider, ModernLifePatch.MOD_ID, existingFileHelper);
    }

    @Override
    protected void addTags() {
//        this.tag(ModTags.Items.GENERAL);
//        this.tag(ModTags.Items.KITCHEN);
//        this.tag(ModTags.Items.BEDCHAMBER);
//        this.tag(ModTags.Items.BEDCHAMBER);
//        this.tag(ModTags.Items.BATHROOM);
//        this.tag(ModTags.Items.BATHROOM);
//        this.tag(ModTags.Items.LOUNGE);
//        this.tag(ModTags.Items.OUTSIDE);
//        this.tag(ModTags.Items.TOOL);
//        this.tag(ModTags.Items.SEAT);
//        this.tag(ModTags.Items.TABLE);
//        this.tag(ModTags.Items.SHELF);
//        this.tag(ModTags.Items.DOOR);
    }
}
