package com.dairymoose.modernlife.core;

import net.minecraft.world.level.block.Block;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.DistExecutor;
import net.minecraftforge.fml.common.Mod;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

@Mod("modernlife")
/* loaded from: outputsrg.jar:com/dairymoose/modernlife/core/ModernLife.class */
public class ModernLife {
    public static final String MODID = "modernlife";
    private static final Logger LOGGER = LogManager.getLogger();

    public ModernLife() {
        DistExecutor.runForDist(() -> {
            return ModernLifeClient::new;
        }, () -> {
            return ModernLifeCommon::new;
        });
    }

    @Mod.EventBusSubscriber(bus = Mod.EventBusSubscriber.Bus.MOD)
    /* loaded from: outputsrg.jar:com/dairymoose/modernlife/core/ModernLife$RegistryEvents.class */
    public static class RegistryEvents {
        @SubscribeEvent
        public static void onBlocksRegistry(RegistryEvent.Register<Block> blockRegistryEvent) {
        }
    }
}
