package com.dairymoose.modernlife.blocks;

import java.util.stream.Stream;
import net.minecraft.core.BlockPos;
import net.minecraft.world.level.BlockGetter;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.state.BlockBehaviour;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.phys.shapes.BooleanOp;
import net.minecraft.world.phys.shapes.CollisionContext;
import net.minecraft.world.phys.shapes.Shapes;
import net.minecraft.world.phys.shapes.VoxelShape;

/* loaded from: outputsrg.jar:com/dairymoose/modernlife/blocks/CoffeeTableBlock.class */
public class CoffeeTableBlock extends SmallTableBlock {
    protected static final VoxelShape SHAPE_NORMAL = (VoxelShape) Stream.of(Block.box(0.01d, 0.0d, 0.01d, 15.99d, 8.0d, 15.99d)).reduce((v1, v2) -> {
        return Shapes.join(v1, v2, BooleanOp.OR);
    }).get();

    public CoffeeTableBlock(Properties p_i48377_1_) {
        super(p_i48377_1_);
    }

    public CoffeeTableBlock(Properties p_i48377_1_, boolean skipDefaultState) {
        super(p_i48377_1_, skipDefaultState);
    }

    @Override // com.dairymoose.modernlife.blocks.SmallTableBlock
    public VoxelShape getShape(BlockState bs, BlockGetter reader, BlockPos pos, CollisionContext sel) {
        return SHAPE_NORMAL;
    }
}
