package com.dairymoose.entity;

import net.minecraft.core.BlockPos;
import net.minecraft.world.entity.Entity;
import net.minecraft.world.level.block.state.BlockState;

/* loaded from: outputsrg.jar:com/dairymoose/entity/RenderableBlock.class */
public class RenderableBlock {
    public BlockPos pos;
    public double relativeX;
    public double relativeY;
    public double relativeZ;
    public BlockState state;
    public float offset = 0.0f;

    public RenderableBlock(Entity e, BlockPos pos, BlockState state) {
        this.pos = pos;
        this.relativeX = pos.getX() - e.blockPosition().getX();
        this.relativeY = pos.getY() - e.blockPosition().getY();
        this.relativeZ = pos.getZ() - e.blockPosition().getZ();
        this.state = state;
    }

    public String toString() {
        return "RenderableBlock [pos=" + this.pos + ", state=" + this.state + "]";
    }
}
