package com.dairymoose.modernlife.tileentities;

import com.dairymoose.modernlife.core.CustomBlocks;
import com.mojang.datafixers.types.Type;
import net.minecraft.core.BlockPos;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.entity.BlockEntity;
import net.minecraft.world.level.block.entity.BlockEntityType;
import net.minecraft.world.level.block.state.BlockState;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/* loaded from: outputsrg.jar:com/dairymoose/modernlife/tileentities/AlarmClockBlockEntity.class */
public class AlarmClockBlockEntity extends BlockEntity {
    public static final BlockEntityType<AlarmClockBlockEntity> ALARM_CLOCK = BlockEntityType.Builder.of(AlarmClockBlockEntity::new, new Block[]{(Block) CustomBlocks.BLOCK_ALARM_CLOCK.get()}).build((Type) null);
    private static final Logger LOGGER = LogManager.getLogger();

    public AlarmClockBlockEntity(BlockPos p_155301_, BlockState p_155302_) {
        super(ALARM_CLOCK, p_155301_, p_155302_);
    }
}
