package com.r3944realms.modernlifepatch.content.blocks.entities;

import com.r3944realms.modernlifepatch.ModernLifePatch;
import com.r3944realms.modernlifepatch.content.blocks.ModBlocks;
import com.r3944realms.modernlifepatch.content.blocks.entities.type.mirror.MirrorBlockEntity;
import net.minecraft.world.level.block.entity.BlockEntityType;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

import java.util.Set;

public class ModBlockEntityType {
    private static final DeferredRegister<BlockEntityType<?>> BLOCK_ENTITY_TYPE
            = DeferredRegister.create(ForgeRegistries.BLOCK_ENTITY_TYPES, ModernLifePatch.MOD_ID);
    @SuppressWarnings("DataFlowIssue")
    public static final RegistryObject<BlockEntityType<MirrorBlockEntity>> MIRROR
            = BLOCK_ENTITY_TYPE.register("mirror", () -> new BlockEntityType<>(MirrorBlockEntity::new, Set.of(ModBlocks.MIRROR.get()), null));
    public static void register(IEventBus bus) {
        BLOCK_ENTITY_TYPE.register(bus);
    }
}
