package com.r3944realms.modernlifepatch.content.blocks.entities.type.mirror;

import com.r3944realms.modernlifepatch.content.blocks.entities.ModBlockEntityType;
import net.minecraft.core.BlockPos;
import net.minecraft.world.level.block.entity.BlockEntity;
import net.minecraft.world.level.block.state.BlockState;

public class MirrorBlockEntity extends BlockEntity {
    public MirrorBlockEntity(BlockPos pPos, BlockState pBlockState) {
        super(ModBlockEntityType.MIRROR.get(), pPos, pBlockState);
    }
}
