package com.r3944realms.modernlifepatch.datagen.provider;

import com.r3944realms.modernlifepatch.ModernLifePatch;
import com.r3944realms.modernlifepatch.content.blocks.ModBlocks;
import net.minecraft.core.HolderLookup;
import net.minecraft.data.PackOutput;
import net.minecraft.tags.BlockTags;
import net.minecraftforge.common.data.BlockTagsProvider;
import net.minecraftforge.common.data.ExistingFileHelper;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.util.concurrent.CompletableFuture;

public class ModBlockTagProvider extends BlockTagsProvider {


    public ModBlockTagProvider(PackOutput output, CompletableFuture<HolderLookup.Provider> lookupProvider, @Nullable ExistingFileHelper existingFileHelper) {
        super(output, lookupProvider, ModernLifePatch.MOD_ID, existingFileHelper);
    }

    @Override
    protected void addTags(HolderLookup.@NotNull Provider pProvider) {
        tag(BlockTags.MINEABLE_WITH_PICKAXE)
                .add(
                        ModBlocks.WHITE_CONCRETE_BARRIER.get(),
                        ModBlocks.ORANGE_CONCRETE_BARRIER.get(),
                        ModBlocks.MAGENTA_CONCRETE_BARRIER.get(),
                        ModBlocks.LIGHT_BLUE_CONCRETE_BARRIER.get(),
                        ModBlocks.YELLOW_CONCRETE_BARRIER.get(),
                        ModBlocks.LIME_CONCRETE_BARRIER.get(),
                        ModBlocks.PINK_CONCRETE_BARRIER.get(),
                        ModBlocks.GRAY_CONCRETE_BARRIER.get(),
                        ModBlocks.LIGHT_GRAY_CONCRETE_BARRIER.get(),
                        ModBlocks.CYAN_CONCRETE_BARRIER.get(),
                        ModBlocks.PURPLE_CONCRETE_BARRIER.get(),
                        ModBlocks.BLUE_CONCRETE_BARRIER.get(),
                        ModBlocks.BROWN_CONCRETE_BARRIER.get(),
                        ModBlocks.GREEN_CONCRETE_BARRIER.get(),
                        ModBlocks.RED_CONCRETE_BARRIER.get(),
                        ModBlocks.BLACK_CONCRETE_BARRIER.get(),
                        ModBlocks.NULL_BLOCK.get(),
                        ModBlocks.ONE_BLOCK.get(),
                        ModBlocks.TWO_BLOCK.get(),
                        ModBlocks.THREE_BLOCK.get(),
                        ModBlocks.FOUR_BLOCK.get(),
                        ModBlocks.FIVE_BLOCK.get(),
                        ModBlocks.SIX_BLOCK.get(),
                        ModBlocks.SEVEN_BLOCK.get(),
                        ModBlocks.EIGHT_BLOCK.get(),
                        ModBlocks.NINE_BLOCK.get(),
                        ModBlocks.ZERO_BLOCK.get()
                );
    }
}
