package com.dairymoose.modernlife.blocks;

import com.dairymoose.modernlife.util.ModernLifeUtil;
import java.util.stream.Stream;
import net.minecraft.core.BlockPos;
import net.minecraft.core.Direction;
import net.minecraft.world.level.BlockGetter;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.state.BlockBehaviour;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.phys.shapes.BooleanOp;
import net.minecraft.world.phys.shapes.CollisionContext;
import net.minecraft.world.phys.shapes.Shapes;
import net.minecraft.world.phys.shapes.VoxelShape;

/* loaded from: outputsrg.jar:com/dairymoose/modernlife/blocks/KitchenDrawerCabinetBlock.class */
public class KitchenDrawerCabinetBlock extends NightStandBlock {
    protected static final VoxelShape SHAPE_SOUTH = (VoxelShape) Stream.of((Object[]) new VoxelShape[]{Block.box(0.05d, 0.15d, 15.51d, 15.95d, 15.975d, 15.51d), Block.box(0.0d, 0.0d, 0.0d, 16.0d, 16.0d, 15.5d), Block.box(1.0d, 1.0d, 15.5d, 15.0d, 11.0d, 16.0d), Block.box(1.0d, 11.5d, 15.5d, 15.0d, 15.0d, 16.0d), Block.box(6.25d, 12.75d, 16.0d, 6.75d, 13.25d, 16.5d), Block.box(6.25d, 12.75d, 16.5d, 10.25d, 13.25d, 17.0d), Block.box(9.75d, 12.75d, 16.0d, 10.25d, 13.25d, 16.5d), Block.box(14.0d, 8.5d, 16.25d, 14.5d, 10.5d, 16.5d), Block.box(14.0d, 10.25d, 16.0d, 14.5d, 10.5d, 16.25d), Block.box(14.0d, 8.5d, 16.0d, 14.5d, 8.75d, 16.25d)}).reduce((v1, v2) -> {
        return Shapes.join((VoxelShape) v1, (VoxelShape) v2, BooleanOp.OR);
    }).get();
    protected static final VoxelShape SHAPE_WEST = ModernLifeUtil.RotateVoxelShapeClockwise(SHAPE_SOUTH);
    protected static final VoxelShape SHAPE_NORTH = ModernLifeUtil.RotateVoxelShapeClockwise(SHAPE_WEST);
    protected static final VoxelShape SHAPE_EAST = ModernLifeUtil.RotateVoxelShapeClockwise(SHAPE_NORTH);

    public KitchenDrawerCabinetBlock(Properties properties) {
        super(properties);
        this.containerDisplayLabel = "Kitchen Drawer Cabinet";
    }

    /* renamed from: com.dairymoose.modernlife.blocks.KitchenDrawerCabinetBlock$1 */
    /* loaded from: outputsrg.jar:com/dairymoose/modernlife/blocks/KitchenDrawerCabinetBlock$1.class */
    static /* synthetic */ class C00301 {
        static final /* synthetic */ int[] $SwitchMap$net$minecraft$core$Direction = new int[Direction.values().length];

        static {
            try {
                $SwitchMap$net$minecraft$core$Direction[Direction.NORTH.ordinal()] = 1;
            } catch (NoSuchFieldError e) {
            }
            try {
                $SwitchMap$net$minecraft$core$Direction[Direction.SOUTH.ordinal()] = 2;
            } catch (NoSuchFieldError e2) {
            }
            try {
                $SwitchMap$net$minecraft$core$Direction[Direction.EAST.ordinal()] = 3;
            } catch (NoSuchFieldError e3) {
            }
            try {
                $SwitchMap$net$minecraft$core$Direction[Direction.WEST.ordinal()] = 4;
            } catch (NoSuchFieldError e4) {
            }
        }
    }

    @Override // com.dairymoose.modernlife.blocks.NightStandBlock
    public VoxelShape getShape(BlockState bs, BlockGetter reader, BlockPos pos, CollisionContext sel) {
        switch (C00301.$SwitchMap$net$minecraft$core$Direction[bs.getValue(NightStandBlock.FACING).ordinal()]) {
            case 1:
                return SHAPE_NORTH;
            case 2:
                return SHAPE_SOUTH;
            case 3:
                return SHAPE_EAST;
            case 4:
                return SHAPE_WEST;
            default:
                return SHAPE_NORTH;
        }
    }
}
